package com.dmb25.consoprotection.domain.model



data class Product(
    val id: Int,
    val gtin: Long,
    val numeroFiche: String,
    val numeroVersion: Int,
    val natureJuridiqueRappel: String,
    val categorieProduit: String,
    val sousCategorieProduit: String,
    val marqueProduit: String,
    val libelle: String,
    val modelesOuReferences: List<String>,
    val identificationProduits: List<IdentificationProduit>,
    val conditionnements: List<String>?,
    val dateDebutCommercialisation: String?,
    val dateDateFinCommercialisation: String?,
    val temperatureConservation: String?,
    val marqueSalubrite: String?,
    val informationsComplementaires: String?,
    val zoneGeographiqueDeVente: List<String>,
    val distributeurs: List<String>,
    val motifRappel: String,
    val risquesEncourus: String,
    val preconisationsSanitaires: String?,
    val descriptionComplementaireRisque: String?,
    val conduitesATenirParLeConsommateur: List<String>,
    val numeroContact: String?,
    val modalitesDeCompensation: List<String>,
    val dateDeFinDeLaProcedureDeRappel: String?,
    val informationsComplementairesPubliques: String?,
    val images: List<String>,
    val lienVersLaListeDesProduits: String?,
    val lienVersLaListeDesDistributeurs: String?,
    val lienVersAffichettePdf: String,
    val lienVersLaFicheRappel: String,
    val rappelGuid: String,
    val datePublication: String,
)
